DEVELOPMENT.md
README.md

First of all I'd like to introduce to you the `DEVELOPMENT.md`. It took me quite a while until I realised my IDE requires Project Lombok in order to be able to build the project. Would be nice to state this out 👍

add 'DEVELOPMENT.md'

---

pom.xml
simulator-archetypes/archetype-jms/src/main/resources/archetype-resources/pom.xml
simulator-archetypes/archetype-mail/src/main/resources/archetype-resources/pom.xml
simulator-archetypes/archetype-rest/src/main/resources/archetype-resources/pom.xml
simulator-archetypes/archetype-swagger/src/main/resources/archetype-resources/pom.xml
simulator-archetypes/archetype-ws/src/main/resources/archetype-resources/pom.xml
simulator-archetypes/archetype-wsdl/src/main/resources/archetype-resources/pom.xml

update `citrus.version=3.1.0`, pretty straight forward 😉

feat(deps): use citrus-core release 3.1.0

---

.github/workflows/lts.yml
pom.xml
simulator-samples/sample-bank-service/src/main/java/org/citrusframework/simulator/sample/scenario/CalculateIban.java
simulator-samples/sample-bank-service/src/main/java/org/citrusframework/simulator/sample/scenario/ValidateIban.java
simulator-samples/sample-bank-service/src/main/java/org/citrusframework/simulator/sample/starter/CalculateStarter.java
simulator-samples/sample-bank-service/src/main/java/org/citrusframework/simulator/sample/starter/ValidateStarter.java
simulator-samples/sample-bank-service/src/test/java/org/citrusframework/simulator/BankServiceSimulatorIT.java
simulator-samples/sample-swagger/src/main/resources/application.properties
simulator-starter/src/main/resources/META-INF/citrus-simulator.properties

citrus `3.2.1` update. also match spring (-boot) versions.

chore(deps): citrus 3.2.0

---

simulator-samples/sample-jms-fax/pom.xml

chore(deps): include jdk17 compatible jaxb-runtime

---

simulator-starter/src/main/java/org/citrusframework/simulator/repository/MessageRepositoryImpl.java
simulator-starter/src/main/java/org/citrusframework/simulator/repository/ScenarioExecutionRepositoryImpl.java
simulator-ui/src/main/resources/static/src/app/components/activity/activity.ts
simulator-ui/src/main/resources/static/src/app/components/messages/messages.ts
simulator-ui/src/main/resources/static/src/app/components/shared/date-time.ts
simulator-ui/src/main/resources/static/src/app/model/filter.ts
simulator-ui/src/main/resources/static/src/app/styles/filter-section.css

The execution pagination was not working properly due to missing backend operation. The current page number has to be multiplied with the given page size.

pagination-fix

---

.github/workflows/release.yml

noticed that the release build still was on JDK 11...

ci: bump release build to jdk 17

---

simulator-starter/pom.xml
simulator-starter/src/test/java/org/citrusframework/simulator/dictionary/InboundXmlDataDictionaryTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/dictionary/OutboundXmlDataDictionaryTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/http/HttpRequestAnnotationMatcherTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/http/HttpRequestAnnotationScenarioMapperTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/http/HttpRequestPathScenarioMapperTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/http/HttpScenarioGeneratorTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/http/SimulatorHttpMessageConverterTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/scenario/mapper/ScenarioMappersTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/service/MessageServiceTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/template/TemplateHelperTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/ws/WsdlScenarioGeneratorTest.java

as you may have noticed, the existing tests in #177 did actually not run at all - just these for the new code. that was intentional! because I planned to migrate these from testng to junit. that's what this PR is about (successor of #177).
the overall coverage is actually around 60%. not even that bad. I've attached it in the zip: [coverage.zip](https://github.com/citrusframework/citrus-simulator/files/12886629/coverage.zip)

simulator starter tests

---

simulator-starter/src/main/java/org/citrusframework/simulator/model/EntityUtils.java
simulator-starter/src/main/java/org/citrusframework/simulator/model/ScenarioExecution.java
simulator-starter/src/main/java/org/citrusframework/simulator/model/TestResult.java
simulator-starter/src/main/java/org/citrusframework/simulator/service/ActivityService.java
simulator-starter/src/test/java/org/citrusframework/simulator/model/EntityTestUtils.java
simulator-starter/src/test/java/org/citrusframework/simulator/model/EntityUtilsTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/model/MessageHeaderTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/model/MessageTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/model/TestParameterTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/model/TestResultTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/repository/MessageRepositoryIT.java
simulator-starter/src/test/java/org/citrusframework/simulator/repository/ScenarioActionRepositoryIT.java
simulator-starter/src/test/java/org/citrusframework/simulator/repository/ScenarioParameterRepositoryIT.java
simulator-starter/src/test/java/org/citrusframework/simulator/service/impl/ScenarioActionServiceImplTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResourceIT.java

Fix an issue with truncation of column values. Adds truncation to ScenarioExecution entity.

fix: TestResult error message truncation

---

simulator-docs/src/main/asciidoc/concepts.adoc
simulator-docs/src/main/asciidoc/installation.adoc
simulator-docs/src/main/asciidoc/intermediate-messages.adoc
simulator-docs/src/main/asciidoc/introduction.adoc
simulator-docs/src/main/asciidoc/rest-api.adoc
simulator-docs/src/main/asciidoc/scenario-mapper.adoc
simulator-docs/src/main/asciidoc/scenarios.adoc
simulator-starter/src/main/java/org/citrusframework/simulator/config/SimulatorConfigurationProperties.java

revising the first three chapters of the simulator docs. as far as I made it today.

Revised simulator documentation - Introduction

---

simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.html
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.spec.ts
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.ts
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.html
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.spec.ts
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.ts
simulator-ui/src/main/webapp/app/entities/message-header/service/message-header.service.ts
simulator-ui/src/main/webapp/app/entities/message/detail/message-detail.component.html
simulator-ui/src/main/webapp/app/entities/message/detail/message-detail.component.ts
simulator-ui/src/main/webapp/app/entities/message/message.model.ts
simulator-ui/src/main/webapp/app/entities/message/service/message.service.ts
simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.html
simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.ts
simulator-ui/src/main/webapp/app/entities/test-result/list/test-result.component.html
simulator-ui/src/main/webapp/app/entities/test-result/list/test-result.component.ts
simulator-ui/src/main/webapp/app/entities/test-result/test-result.model.ts

message headers on message:
visual execution status indicators:

ui improvements

---

simulator-docs/src/main/asciidoc/concepts.adoc
simulator-samples/sample-combined/pom.xml
simulator-samples/sample-combined/src/main/java/org/citrusframework/simulator/sample/Simulator.java
simulator-samples/sample-combined/src/main/java/org/citrusframework/simulator/sample/scenario/DefaultScenario.java
simulator-samples/sample-combined/src/main/java/org/citrusframework/simulator/sample/scenario/GoodNightScenario.java
simulator-samples/sample-combined/src/main/resources/application.properties
simulator-samples/sample-combined/src/test/java/org/citrusframework/simulator/EndpointConfig.java
simulator-samples/sample-combined/src/test/java/org/citrusframework/simulator/SimulatorRestIT.java
simulator-samples/sample-combined/src/test/java/org/citrusframework/simulator/SimulatorWebServiceIT.java
simulator-samples/sample-jms-fax/src/main/resources/application.properties
simulator-samples/sample-ws-client/src/main/resources/application.properties
simulator-starter/pom.xml
simulator-starter/src/main/java/org/citrusframework/simulator/http/SimulatorRestAutoConfiguration.java
simulator-starter/src/main/java/org/citrusframework/simulator/ws/SimulatorWebServiceAutoConfiguration.java
simulator-starter/src/main/java/org/citrusframework/simulator/ws/SimulatorWebServiceLoggingAutoConfiguration.java
simulator-starter/src/test/java/org/citrusframework/simulator/ws/SimulatorWebServiceAutoConfigurationIT.java
simulator-starter/src/test/java/org/citrusframework/simulator/ws/SimulatorWebServiceAutoConfigurationSpringIT.java
simulator-ui/src/main/java/org/citrusframework/simulator/ui/config/SecurityConfiguration.java
simulator-ui/src/main/java/org/citrusframework/simulator/ui/filter/SpaWebFilter.java
simulator-ui/src/main/resources/META-INF/spring-configuration-metadata.json
simulator-ui/src/test/java/org/citrusframework/simulator/ui/filter/SpaWebFilterTest.java

rest and ws combined

---

simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.html
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.spec.ts
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.ts
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.html
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.spec.ts
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.ts
simulator-ui/src/main/webapp/app/entities/message-header/service/message-header.service.ts
simulator-ui/src/main/webapp/app/entities/message/detail/message-detail.component.html
simulator-ui/src/main/webapp/app/entities/message/detail/message-detail.component.ts
simulator-ui/src/main/webapp/app/entities/message/message.model.ts
simulator-ui/src/main/webapp/app/entities/message/service/message.service.ts
simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.html
simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.ts
simulator-ui/src/main/webapp/app/entities/test-result/list/test-result.component.html
simulator-ui/src/main/webapp/app/entities/test-result/list/test-result.component.ts
simulator-ui/src/main/webapp/app/entities/test-result/test-result.model.ts

thought I did commit this already.. but found it in a `git fetch` and was wondering where it went. anyway:
* status-badge indicator for scenario executions
* status-badge indicator for test results
* message-header list in headers detail view

visual improvents

---

simulator-starter/src/main/java/org/citrusframework/simulator/endpoint/EndpointMessageHandler.java
simulator-starter/src/main/java/org/citrusframework/simulator/listener/SimulatorStatusListener.java
simulator-starter/src/main/java/org/citrusframework/simulator/model/TestParameter.java
simulator-starter/src/main/java/org/citrusframework/simulator/repository/MessageHeaderRepository.java
simulator-starter/src/main/java/org/citrusframework/simulator/repository/MessageRepository.java
simulator-starter/src/main/java/org/citrusframework/simulator/repository/ScenarioActionRepository.java
simulator-starter/src/main/java/org/citrusframework/simulator/repository/ScenarioExecutionRepository.java
simulator-starter/src/main/java/org/citrusframework/simulator/repository/ScenarioParameterRepository.java
simulator-starter/src/main/java/org/citrusframework/simulator/repository/TestParameterRepository.java
simulator-starter/src/main/java/org/citrusframework/simulator/scenario/ScenarioRunner.java
simulator-starter/src/main/java/org/citrusframework/simulator/service/ActivityService.java
simulator-starter/src/main/java/org/citrusframework/simulator/service/MessageHeaderService.java
simulator-starter/src/main/java/org/citrusframework/simulator/service/MessageService.java
simulator-starter/src/main/java/org/citrusframework/simulator/service/ScenarioActionService.java
simulator-starter/src/main/java/org/citrusframework/simulator/service/ScenarioExecutionService.java
simulator-starter/src/main/java/org/citrusframework/simulator/service/ScenarioParameterService.java
simulator-starter/src/main/java/org/citrusframework/simulator/service/TestParameterService.java
simulator-starter/src/main/java/org/citrusframework/simulator/service/impl/MessageServiceImpl.java
simulator-starter/src/main/java/org/citrusframework/simulator/service/impl/ScenarioExecutionServiceImpl.java
simulator-starter/src/main/java/org/citrusframework/simulator/service/impl/TestParameterServiceImpl.java
simulator-starter/src/test/java/org/citrusframework/simulator/repository/MessageRepositoryIT.java
simulator-starter/src/test/java/org/citrusframework/simulator/repository/ScenarioParameterRepositoryIT.java
simulator-starter/src/test/java/org/citrusframework/simulator/repository/TestParameterRepositoryIT.java
simulator-starter/src/test/java/org/citrusframework/simulator/service/impl/DefaultScenarioExecutorServiceImplTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/service/impl/MessageServiceImplTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/service/impl/ScenarioExecutionServiceImplTest.java
simulator-starter/src/test/java/org/citrusframework/simulator/service/impl/TestParameterServiceImplTest.java

Remove monolithic `ActivityService`, entity-related code has been moved into the respective service classes.

Remove most of "Activity" service

---

simulator-spring-boot/src/main/java/org/citrusframework/simulator/http/HttpScenarioActionBuilder.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/http/HttpScenarioActionBuilderTest.java

follow up of https://github.com/citrusframework/citrus-simulator/pull/221

chore: cleanup send helpers

---

simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/impl/DefaultScenarioExecutorServiceImpl.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/DefaultScenarioExecutorServiceImplTest.java

I replaced the reflective execution by simply calling the interface method.

fix(#230): Multiple scenario calls on scenarios overriding run method

---

simulator-docs/src/main/asciidoc/rest-api.adoc
simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/MessageHeaderResource.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/MessageResource.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/ScenarioActionResource.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResource.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/ScenarioParameterResource.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/ScenarioResource.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/TestParameterResource.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/TestResultResource.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/events/ScenariosReloadedEventIT.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/repository/MessageHeaderRepositoryIT.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/repository/MessageRepositoryIT.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/repository/ScenarioActionRepositoryIT.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/repository/ScenarioParameterRepositoryIT.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/MessageHeaderServiceImplTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/MessageServiceImplTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/ScenarioActionServiceImplTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/ScenarioExecutionServiceImplTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/ScenarioParameterServiceImplTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioResourceIT.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioResourceTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/util/PaginationUtilTest.java

scenario-search by name; backend implementation. as part of #233.

feat(simulator): search by scenario name

---

simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/ScenarioExecution.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/ScenarioActionService.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/ScenarioActionServiceImplTest.java
simulator-ui/src/main/webapp/app/core/util/operator.spec.ts
simulator-ui/src/main/webapp/app/core/util/operators.ts
simulator-ui/src/main/webapp/app/core/util/sort-parameters.type.ts
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.html
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.spec.ts
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.ts
simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.ts
simulator-ui/src/main/webapp/app/entities/message/detail/message-detail.component.html
simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/message-table.component.html
simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/message-table.component.spec.ts
simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/message-table.component.ts
simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-execution-detail.component.html
simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-execution-detail.component.ts
simulator-ui/src/main/webapp/app/entities/scenario-execution/scenario-execution.model.ts

more details visible on scenario executions page. fixed a bug where the scenario executions were not correctly linked.

scenario execution details

---

simulator-spring-boot/src/main/java/org/citrusframework/simulator/config/SimulatorConfigurationProperties.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/AbstractAuditingEntity.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/Message.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/MessageHeader.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/ScenarioAction.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/ScenarioExecution.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/ScenarioParameter.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/TestParameter.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/TestResult.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/model/EntityTestUtils.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/model/EntityUtilsTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/model/MessageHeaderTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/model/MessageTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/model/ScenarioActionTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/model/ScenarioExecutionTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/model/ScenarioParameterTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/model/TestParameterIdTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/model/TestParameterTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/model/TestResultTest.java

a bug that lead to inconsistency because of failure in hash codes and equals of data (custom simulator, not the citrus core).

domain classes

---

simulator-ui/src/main/webapp/app/entities/message-header/list/message-header-table.component.html
simulator-ui/src/main/webapp/app/entities/message/list/message.component.html
simulator-ui/src/main/webapp/app/entities/scenario-action/list/scenario-action.component.html
simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/message-table.component.html
simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.html
simulator-ui/src/main/webapp/app/entities/scenario-parameter/list/scenario-parameter.component.html
simulator-ui/src/main/webapp/app/entities/test-parameter/list/test-parameter.component.html
simulator-ui/src/main/webapp/app/entities/test-result/list/test-result.component.html
simulator-ui/src/main/webapp/app/home/test-result-summary.component.html
simulator-ui/src/main/webapp/app/scenario/list/scenario.component.html

- updated all buttons with a <a> tag to allow to use the middle mouse click

fix(#261): open window in new tab

---

simulator-spring-boot/src/main/java/org/citrusframework/simulator/common/TimeProvider.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/AbstractAuditingEntity.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/impl/ScenarioActionServiceImpl.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/impl/ScenarioExecutionServiceImpl.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/model/AbstractAuditingEntityIT.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/ScenarioActionServiceImplTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/impl/ScenarioExecutionServiceImplTest.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResourceIT.java

The CreatedDate was always off by 2 Hours.
FIxes #282

use ZonedTime on AuditingEntity

---

.github/workflows/frontend.yml
.github/workflows/lts.yml
.github/workflows/nightly.yml
pom.xml
simulator-spring-boot/src/main/java/org/citrusframework/simulator/ws/WsdlScenarioGenerator.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/ws/WsdlScenarioGeneratorTest.java

* spring-boot 3.3.2
* spring 6.3.2
* node and npm LTS

update to citrus v3.4.1

---

pom.xml
simulator-docs/src/main/asciidoc/rest-api.adoc
simulator-samples/sample-rest/src/test/java/org/citrusframework/simulator/SimulatorRestIT.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/CriteriaQueryUtils.java
simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/ScenarioExecutionQueryService.java
simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResourceIT.java

and update to latest citrus release.

count unique results

---

pom.xml
simulator-samples/pom.xml
simulator-ui/pom.xml

and a little fix for the simulator UI where `AP_VERSION` must be copied at build time.

depencency updates

---

simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/ScenarioExecutionQueryService.java

part 2 of performance improvements, based on https://github.com/citrusframework/citrus-simulator/pull/319

group similar queries
