simulator-samples/sample-bank-service/src/main/java/com/consol/citrus/simulator/sample/config/HttpClientConfig.java, simulator-samples/sample-jms-fax/src/main/java/com/consol/citrus/simulator/sample/jms/async/Simulator.java, simulator-starter/src/main/java/com/consol/citrus/simulator/endpoint/SimulatorEndpointAutoConfiguration.java, simulator-starter/src/main/java/com/consol/citrus/simulator/http/SimulatorRestAutoConfiguration.java, simulator-starter/src/main/java/com/consol/citrus/simulator/jms/SimulatorJmsAutoConfiguration.java, simulator-starter/src/main/java/com/consol/citrus/simulator/ws/SimulatorWebServiceAutoConfiguration.java, simulator-starter/src/main/java/com/consol/citrus/simulator/ws/SimulatorWebServiceClientAutoConfiguration.java
Fix for the "bean-overriding" bug, reported in #15 ..
The following bean was registered by Citrus-Simulator:
```java
com.consol.citrus.simulator.ws.SimulatorWebServiceAutoConfiguration {
[...]
public ServletRegistrationBean messageDispatcherServlet (
[...]
```
which conflicted with Spring Boot's autoconfiguration (`spring-boot-autoconfiguration`):
```java
org.springframework.boot.autoconfigure.webservices.WebServicesAutoConfiguration {
[...]
public ServletRegistrationBean<MessageDispatcherServlet> messageDispatcherServlet (
[...]
```
Therefore the Citrus-Simulator bean is now named `simulatorServletRegistrationBean` and those beans can co-exist.
=> Fix `SimulatorWebServiceAutoConfiguration.java`'s naming conventions.

scripts/build.sh
The "main" build skips integration tests, since those are executed separately in subsequent steps. If the Sonar env is not available, integration tests should be skipped as well.
=> Skip ITs for main project build w/o Sonarqube

.travis.yml, simulator-samples/pom.xml, simulator-samples/sample-swagger/src/test/java/com/consol/citrus/simulator/SimulatorRestIT.java, simulator-samples/sample-swagger/src/test/resources/citrus-context.xml, simulator-starter/src/main/java/com/consol/citrus/simulator/http/SimulatorHttpMessageConverter.java, simulator-starter/src/main/java/com/consol/citrus/simulator/http/SimulatorRestAutoConfiguration.java, simulator-starter/src/main/resources/META-INF/citrus-simulator.properties, simulator-starter/src/test/java/com/consol/citrus/simulator/http/SimulatorHttpMessageConverterTest.java, simulator-ui/src/main/resources/static/package-lock.json
- Add special simulator message converter delegating to Citrus message converter
- Reactivate Swagger samples (were failing because of that issue)
- Make sure simulator UI api calls are fine, too
- Fix api management info endpoint URI
=> Fixed http message converters after update to Spring 5.x

README.md, pom.xml
Uses the latest Spring versions that are compatible with those used in Citrus core framework. Using even newer versions might lead to runtime errors because Citrus core framework is not supporting those versions.
Versions used now are Spring 5.0.15 and Spring Boot 2.0.9
=> chore: Bump dependency versions to latest

simulator-starter/src/main/java/com/consol/citrus/simulator/service/MessageService.java
in order to solve the problems mentioned in #69. We experienced them too and fixed it by overriding the bean with a `@primary`. this is clearly a better solution.
=> #69 filter header values for null or empty strings.

simulator-samples/sample-rest/src/main/java/com/consol/citrus/simulator/sample/scenario/AbstractGreetingScenario.java, simulator-samples/sample-rest/src/main/java/com/consol/citrus/simulator/sample/scenario/DefaultGreetingScenario.java, simulator-samples/sample-rest/src/main/java/com/consol/citrus/simulator/sample/scenario/FriendlyHelloScenario.java, simulator-samples/sample-rest/src/main/java/com/consol/citrus/simulator/sample/scenario/HelloScenario.java, simulator-samples/sample-rest/src/main/java/com/consol/citrus/simulator/sample/scenario/HowdyScenario.java, simulator-samples/sample-rest/src/test/java/com/consol/citrus/simulator/SimulatorRestIT.java, simulator-starter/src/main/java/com/consol/citrus/simulator/service/ScenarioExecutionService.java
This PR includes the pure fix for #46 
The WIP code cleanup that required more regression testing has been moved to a separate branch that can be merged later on (https://github.com/citrusframework/citrus-simulator/tree/chore/46/code-cleanup).
=> fix(#46): Fixed ScenarioExecutionService to execute inherited run implementations

pom.xml
- Fix log4j2 version coming from spring-boot-starter-logging
=> chore: Bump log4j2 version to 2.15.0

simulator-starter/src/main/java/org/citrusframework/simulator/model/MessageHeader.java, simulator-starter/src/main/java/org/citrusframework/simulator/model/ScenarioParameter.java
When building my own app based on the REST archetype, I noticed a bunch of hibernate related errors running schema migrations which were caused by exceptions such as:
```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table message_header (header_id bigint generated by default as identity, name varchar(255) not null, [*]value varchar(255) not null, message_message_id bigint, primary key (header_id))"; expected "identifier"; SQL statement:
create table message_header (header_id bigint generated by default as identity, name varchar(255) not null, value varchar(255) not null, message_message_id bigint, primary key (header_id))
```
What it comes down to is that there are several column names clashing with reserved keywords (notice the asterisk …
=> Fix reserved keywords in models

simulator-starter/src/main/java/org/citrusframework/simulator/controller/ActivityController.java, simulator-starter/src/main/java/org/citrusframework/simulator/model/AbstractAuditingEntity.java, simulator-starter/src/main/java/org/citrusframework/simulator/model/Message.java, simulator-starter/src/main/java/org/citrusframework/simulator/model/MessageFilter.java, simulator-starter/src/main/java/org/citrusframework/simulator/model/MessageHeader.java, simulator-starter/src/main/java/org/citrusframework/simulator/model/ScenarioAction.java, simulator-starter/src/main/java/org/citrusframework/simulator/model/ScenarioExecution.java, simulator-starter/src/main/java/org/citrusframework/simulator/model/ScenarioParameter.java, simulator-starter/src/main/java/org/citrusframework/simulator/repository/ScenarioExecutionRepository.java, simulator-starter/src/main/java/org/citrusframework/simulator/repository/ScenarioExecutionRepositoryImpl.java, simulator-starter/src/main/java/org/citrusframework/simulator/service/ActivityService.java, simulator-starter/src/main/java/org/citrusframework/simulator/service/MessageService.java, simulator-starter/src/main/java/org/citrusframework/simulator/service/QueryFilterAdapterFactory.java, simulator-starter/src/test/java/org/citrusframework/simulator/service/MessageRepositoryTest.java, simulator-starter/src/test/java/org/citrusframework/simulator/service/MessageServiceTest.java, simulator-starter/src/test/java/org/citrusframework/simulator/service/ScenarioExecutionRepositoryTest.java
all entities which do not have any timing informatin (e.g. `startDate` or `endDate`) did now receive `createdDate` as well as `lastModifiedDate` information.
closes #166.
=> feat(#166): auditted entities

simulator-docs/src/main/asciidoc/concepts.adoc, simulator-starter/src/main/java/org/citrusframework/simulator/config/SimulatorConfigurationProperties.java, simulator-starter/src/main/java/org/citrusframework/simulator/service/ScenarioExecutionService.java
Adds a property to the scenario configuration, which was previously hardcoded to 10, and now allows specifying the number of threads for async scenario execution. Fixes #167.
=> feat(#167): add scenario executor thread config property

pom.xml, simulator-starter/pom.xml
* [CVE-2022-4065](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-4065) reported in `org.testng:testng:7.5.1`
* [CVE-2022-45868](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-45868) reported in `com.h2database.h2:2.1.114`
=> fix(deps): transitive dependency vulnerabilities

simulator-starter/pom.xml, simulator-ui/src/main/webapp/swagger-ui/index.html
swagger-ui was not accessible. will update documentation accordingly, with new URLs. see #198 for more information.
=> fix(simulator-starter): swagger-api and -ui

simulator-samples/sample-bank-service/src/main/java/org/citrusframework/simulator/sample/scenario/CalculateIban.java, simulator-samples/sample-bank-service/src/main/java/org/citrusframework/simulator/sample/scenario/ValidateIban.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/dictionary/OutboundXmlDataDictionary.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/http/HttpScenarioActionBuilder.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/http/HttpScenarioActionBuilderTest.java
we have a lot of these in our code:
```java
scenario.$(scenario.http()
.send()
.response(HttpStatus.OK)
.message()
.contentType(MediaType.APPLICATION_JSON_VALUE));
.body(myJsonObject)
```
the following would help for sure:
```java
scenario.$(
scenario.http()
.sendOkJson(myJsonObject)
);
```
more to come in the future, maybe...
=> easy response helpers

simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.spec.ts, simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.ts, simulator-ui/src/main/webapp/app/scenario-result/scenario-result.component.html, simulator-ui/src/main/webapp/app/scenario-result/scenario-result.component.spec.ts, simulator-ui/src/main/webapp/app/scenario-result/scenario-result.component.ts, simulator-ui/src/main/webapp/app/scenario/list/scenario.component.html, simulator-ui/src/main/webapp/app/scenario/list/scenario.component.spec.ts, simulator-ui/src/main/webapp/app/scenario/list/scenario.component.ts
>  Default Sorting of Executions: The default display seems to list the oldest Executions at the top. It would be more user-friendly to have an option to customize this default sorting to suit individual preferences.
=> sortable scenario executions

simulator-spring-boot/lombok.config, simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/Message.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/MessageHeader.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/ScenarioAction.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/ScenarioExecution.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/ScenarioParameter.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/TestParameter.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/TestResult.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/repository/MessageRepository.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/repository/ScenarioExecutionRepository.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/repository/TestResultRepository.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/CriteriaQueryUtils.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/MessageQueryService.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/ScenarioExecutionQueryService.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/TestResultQueryService.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/MessageQueryServiceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/ScenarioExecutionQueryServiceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/TestResultQueryServiceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/MessageResourceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResourceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioParameterResourceIT.java
@tschlat & @novarx this is a draft pull-request that outlines a solution to the problem describe in #255. I am open to discuss this solution with you, so we can finish the implementation for the other endpoints afterwards.
=> remove in memory pagination

simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/MessageQueryService.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/ScenarioExecutionQueryService.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/TestResultQueryService.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/MessageQueryServiceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/ScenarioExecutionQueryServiceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/TestResultQueryServiceIT.java, simulator-ui/src/main/webapp/app/entities/message-header/list/message-header.component.ts, simulator-ui/src/main/webapp/app/entities/message/list/message.component.ts, simulator-ui/src/main/webapp/app/entities/navigation-util.spec.ts, simulator-ui/src/main/webapp/app/entities/navigation-util.ts, simulator-ui/src/main/webapp/app/entities/scenario-action/list/scenario-action.component.ts, simulator-ui/src/main/webapp/app/entities/scenario-execution/list/scenario-execution.component.ts, simulator-ui/src/main/webapp/app/entities/scenario-parameter/list/scenario-parameter.component.ts, simulator-ui/src/main/webapp/app/entities/test-parameter/list/test-parameter.component.ts, simulator-ui/src/main/webapp/app/entities/test-result/list/test-result.component.ts, simulator-ui/src/main/webapp/app/scenario-result/scenario-execution-filter.component.spec.ts, simulator-ui/src/main/webapp/app/scenario-result/scenario-execution-filter.component.ts, simulator-ui/src/main/webapp/app/scenario-result/scenario-result.component.spec.ts, simulator-ui/src/main/webapp/app/scenario-result/scenario-result.component.ts, simulator-ui/src/main/webapp/app/scenario/list/scenario.component.ts
merge query params with existing ones, so page does not flick back to old params when navigating with filters.
also found a bug in the backend while clicking throught the UI. the whole pagination object was passed to the subsequent query, instead of only the sorting parameter.
closes #258.
=> simulator UI infinity loop fix

simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-actions-table.component.html, simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-actions-table.component.spec.ts, simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-actions-table.component.ts, simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-execution-detail.component.html, simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-execution-detail.component.ts, simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-messages-table.component.html, simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-messages-table.component.spec.ts, simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-messages-table.component.ts, simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-parameters-table.component.html, simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-parameters-table.component.spec.ts, simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-parameters-table.component.ts, simulator-ui/src/main/webapp/app/entities/scenario-execution/scenario-execution.model.ts
last improvements for the scenario details view. makes it more or less equal to the "old" view. see issue for more information. closes #233 for the time being.
=> scenario details

simulator-spring-boot/src/main/java/org/citrusframework/simulator/endpoint/SimulatorEndpointAutoConfiguration.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/http/SimulatorRestAutoConfiguration.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/jms/SimulatorJmsAutoConfiguration.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/ws/SimulatorWebServiceAutoConfiguration.java
so when someone extends any of these bean configuration classes, he can use the bean name qualifier.
=> bean name access

pom.xml
@christophd remember to include `-DskipFrontend=false` when releasing the project. I think you have to commit it somewhere into the release scripts. but I've honestly never taken the time to understand them 😉
=> include citrus v4.2.1

simulator-spring-boot/src/main/java/org/citrusframework/simulator/repository/MessageRepository.java
since the relation of `ScenarioExecution` to `TestResult` is now 1 to 1, we can simply fetch this with all `Message` entities.
=> chore: resolve nested scenario execution entities

simulator-spring-boot/src/main/java/org/citrusframework/simulator/model/TestResult.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/TestResultResourceIT.java
Added a cascade all to TestResult and ScenarioExecution relation to propagate the delete of the TestReuslt to the ScenarioExecution
=> fix(#281): fix delete test-result in backend

simulator-ui/package-lock.json, simulator-ui/package.json, simulator-ui/src/main/webapp/app/app.module.ts, simulator-ui/src/main/webapp/app/entities/message/detail/message-detail.component.html, simulator-ui/src/main/webapp/app/entities/message/detail/message-detail.component.scss, simulator-ui/src/main/webapp/app/entities/message/detail/message-detail.component.ts, simulator-ui/src/main/webapp/app/entities/message/list/message.component.html, simulator-ui/src/main/webapp/app/entities/message/list/message.component.ts, simulator-ui/src/main/webapp/app/entities/message/route/message-routing-resolve.service.spec.ts, simulator-ui/src/main/webapp/app/entities/message/route/message-routing-resolve.service.ts, simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-messages-table.component.html, simulator-ui/src/main/webapp/app/entities/scenario-execution/detail/scenario-messages-table.component.ts, simulator-ui/src/main/webapp/app/shared/code-formatter.service.spec.ts, simulator-ui/src/main/webapp/app/shared/code-formatter.service.ts, simulator-ui/src/main/webapp/content/scss/vendor.scss
All `Message` payloads are now code-highlighted:
That is also true for `Message` details. There within the code is even formatted! For XML and JSON right now (more would be possible, but I don't know if its asked for).
=> code highlighting in message payloads

simulator-spring-boot/src/main/java/org/citrusframework/simulator/repository/ScenarioExecutionRepository.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResource.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/TechnicalStructureTest.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResourceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResourceTest.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioResourceTest.java
- [feat: optionally include all message headers in scenario execution response](https://github.com/citrusframework/citrus-simulator/commit/d8e4c5efb8ca7c035d2682c615b0d0e3aea8c575)
=> scenario rest api params

pom.xml, simulator-samples/sample-swagger/src/main/resources/application.properties, simulator-spring-boot/pom.xml, simulator-spring-boot/src/main/resources/META-INF/citrus-simulator.properties
requires https://github.com/citrusframework/citrus/pull/1270.
=> update spring-boot to v3.4.0

simulator-docs/src/main/asciidoc/rest-api.adoc, simulator-spring-boot/src/main/java/org/citrusframework/simulator/repository/ScenarioExecutionRepository.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/ScenarioExecutionQueryService.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResource.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/ScenarioExecutionQueryServiceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/MessageHeaderResourceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResourceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResourceTest.java
this makes loading `ScenarioExecutions` "standalone" by default. no additional entities will be fetched without defined query params. wheres previously the whole entity was fetched including all relationships. superfluous information was only stripped afterwards.
the standard sql is:
```sql
select se1_0.execution_id,
se1_0.end_date,
se1_0.scenario_name,
se1_0.start_date,
tr1_0.id,
tr1_0.class_name,
tr1_0.created_date,
tr1_0.error_message,
tr1_0.failure_type,
tr1_0.last_modified_date,
tr1_0.stack_trace,
tr1_0.status,
tr1_0.test_name
from scenario_execution se1_0
left join test_result tr1_0 on tr1_0.id = se1_0.test_result_id
where se1_0.execution_id in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
order by se1_0.execution_id
```
=> improved scenario execution endpoint fetch performance

pom.xml, simulator-spring-boot/src/main/java/org/citrusframework/simulator/repository/MessageRepository.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/repository/TestResultRepository.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/CriteriaQueryUtils.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/MessageQueryService.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/QueryService.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/ScenarioExecutionQueryService.java, simulator-spring-boot/src/main/java/org/citrusframework/simulator/service/TestResultQueryService.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/service/ScenarioExecutionQueryServiceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/ScenarioExecutionResourceIT.java, simulator-spring-boot/src/test/java/org/citrusframework/simulator/web/rest/TransactionUtils.java
last query refactoring pr, addition to:
* https://github.com/citrusframework/citrus-simulator/pull/319 and
* https://github.com/citrusframework/citrus-simulator/pull/322
=> sql query refactoring part III
